services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./configs/prometheus-config.yml:/etc/prometheus/prometheus.yml
      - ./.data/prometheus:/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./configs/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./configs/loki-config.yml:/mnt/config/loki-config.yml
      - ./.data/loki:/tmp
    ports:
      - "3100:3100"
    command: -config.file=/mnt/config/loki-config.yml
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./configs/promtail-config.yml:/mnt/config/promtail-config.yml
      - ./.data:/mnt/data
    depends_on:
      - loki
    command: -config.file=/mnt/config/promtail-config.yml
  structurizr:
    image: structurizr/lite:latest
    container_name: structurizr
    ports:
      - 7200:8080
    volumes:
      - ./docs:/usr/local/structurizr
