package cillio-node:addition@0.1.0;

interface types {
    record inputs {
        a: f32,
        b: f32,
    } 
    record outputs {
        sum: f32,
    }
    variant error {
        process-error(string),
    }
}

world addition {
    use types.{inputs, outputs, error};
    export process: func(in: inputs) -> result<outputs, error>;
}
