// Generated by `wit-bindgen` 0.25.0. DO NOT EDIT!
// Options used:
pub type Inputs = cillio_node::log_number::types::Inputs;
pub type Error = cillio_node::log_number::types::Error;
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_process_cabi<T: Guest>(arg0: f32) -> *mut u8 {
    #[cfg(target_arch = "wasm32")]
    _rt::run_ctors_once();
    let result0 = T::process(cillio_node::log_number::types::Inputs { number: arg0 });
    let ptr1 = _RET_AREA.0.as_mut_ptr().cast::<u8>();
    match result0 {
        Some(e) => {
            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
            use cillio_node::log_number::types::Error as V3;
            match e {
                V3::ProcessError(e) => {
                    *ptr1.add(4).cast::<u8>() = (0i32) as u8;
                    let vec2 = (e.into_bytes()).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(12).cast::<usize>() = len2;
                    *ptr1.add(8).cast::<*mut u8>() = ptr2.cast_mut();
                }
            }
        }
        None => {
            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
        }
    };
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_process<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => (),
        _ => {
            let l1 = i32::from(*arg0.add(4).cast::<u8>());
            match l1 {
                _ => {
                    let l2 = *arg0.add(8).cast::<*mut u8>();
                    let l3 = *arg0.add(12).cast::<usize>();
                    _rt::cabi_dealloc(l2, l3, 1);
                }
            }
        }
    }
}
pub trait Guest {
    fn process(in_: Inputs) -> Option<Error>;
}
#[doc(hidden)]

macro_rules! __export_world_log_number_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[export_name = "process"]
    unsafe extern "C" fn export_process(arg0: f32,) -> *mut u8 {
      $($path_to_types)*::_export_process_cabi::<$ty>(arg0)
    }
    #[export_name = "cabi_post_process"]
    unsafe extern "C" fn _post_return_process(arg0: *mut u8,) {
      $($path_to_types)*::__post_return_process::<$ty>(arg0)
    }
  };);
}
#[doc(hidden)]
pub(crate) use __export_world_log_number_cabi;
#[repr(align(4))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 16]);
static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 16]);
#[allow(dead_code)]
pub mod cillio_node {
    #[allow(dead_code)]
    pub mod log_number {
        #[allow(dead_code, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            #[cfg(target_arch = "wasm32")]
            static __FORCE_SECTION_REF: fn() =
                super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct Inputs {
                pub number: f32,
            }
            impl ::core::fmt::Debug for Inputs {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("Inputs")
                        .field("number", &self.number)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub enum Error {
                ProcessError(_rt::String),
            }
            impl ::core::fmt::Debug for Error {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    match self {
                        Error::ProcessError(e) => {
                            f.debug_tuple("Error::ProcessError").field(e).finish()
                        }
                    }
                }
            }
        }
    }
}
mod _rt {
    pub use alloc_crate::string::String;

    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr as *mut u8, layout);
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}

/// Generates `#[no_mangle]` functions to export the specified type as the
/// root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_log_number_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::__export_world_log_number_cabi!($ty with_types_in $($path_to_types_root)*);
  )
}
#[doc(inline)]
pub(crate) use __export_log_number_impl as export;

#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.25.0:log-number:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 343] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xd6\x01\x01A\x02\x01\
A\x09\x01B\x04\x01r\x01\x06numberv\x04\0\x06inputs\x03\0\0\x01q\x01\x0dprocess-e\
rror\x01s\0\x04\0\x05error\x03\0\x02\x03\x01\"cillio-node:log-number/types@0.1.0\
\x05\0\x02\x03\0\0\x06inputs\x03\0\x06inputs\x03\0\x01\x02\x03\0\0\x05error\x03\0\
\x05error\x03\0\x03\x01k\x04\x01@\x01\x02in\x02\0\x05\x04\0\x07process\x01\x06\x04\
\x01'cillio-node:log-number/log-number@0.1.0\x04\0\x0b\x10\x01\0\x0alog-number\x03\
\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.208.1\x10wit-\
bindgen-rust\x060.25.0";

#[inline(never)]
#[doc(hidden)]
#[cfg(target_arch = "wasm32")]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
