[package]
name = "cillio-graph-component"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wit-bindgen-rt = { version = "0.26.0", features = ["bitflags"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "cillio:cillio-graph-component"

[package.metadata.component.target]
path = "../../wit/graph"

[package.metadata.component.dependencies]

