[package]
name = "cillio-emit-number-node"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen-rt = { version = "0.26.0", features = ["bitflags"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "cillio-node:emit-number"

[package.metadata.component.dependencies]
