[package]
name = "cillio-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
cillio-config = { path = "../cillio-config" }
thiserror = "1.0.61"
